### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by Kzalca** [CjangCjengh/NovelpiaDownloader#27]
Logging in isn't working despite having the right password. I'm able to login into the website and access it but when using the app it only shows 'Failed Login!' Tried using a VPN and a different PC but still nothing.
Anybody else having this problem?

Also, does anyone know how to use the LOGINKEY? I was wondering if I could use that instead as an alternative.

![failedlogin](https://github.com/user-attachments/assets/ee4d47d8-4445-4f30-b54c-5aba9e5e58ba)

**Comment by GTL-BB** [comment]
I have the same issue.

**Comment by Kzalca** [comment]
> I have the same issue.

It just fixed itself on my end. You should try it again as well.

For anyone in the future who sees this, the issue just fixed itself after a day or so! No need to panic.
