### ISSUE TITLE
Epub creating issue

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [CjangCjengh/NovelpiaDownloader#5]
After downloading all the chapters the logs then show downloading image, but after waiting it, the program just force close itself and no epub were created.

Also appreciate the update thanks.

**Comment by CjangCjengh** [comment]
I didn't encounter such issue during testing

**Comment by YukinoshitaYukino123** [comment]
Is there a way for me to give you the error log?

**Comment by CjangCjengh** [comment]
OK. I have fixed it.

**Comment by YukinoshitaYukino123** [comment]
Now it works, I really appreciate your hard works thank you
